-- MySQL schema for the password manager
-- Import with: mysql -u root -p < schema.sql

DROP DATABASE IF EXISTS password_manager;
CREATE DATABASE password_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE password_manager;

CREATE TABLE USER (
    UserID       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Username     VARCHAR(64)  NOT NULL UNIQUE,
    Email        VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Token        VARCHAR(255) NULL,
    Salt         VARCHAR(255) NULL,
    CreatedAt    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE VAULT (
    VaultID   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID    INT UNSIGNED NOT NULL,
    VaultName VARCHAR(128) NOT NULL,
    CreatedAt TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vault_user FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE VAULT_ITEM (
    ItemID    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    VaultID   INT UNSIGNED NOT NULL,
    Title     VARCHAR(255) NOT NULL,
    ItemType  ENUM('PASSWORD','TOTP','PASSKEY','SECURE_NOTE') NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_item_vault FOREIGN KEY (VaultID) REFERENCES VAULT(VaultID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PASSWORD (
    ItemID       INT UNSIGNED PRIMARY KEY,
    UsernameEnc  VARBINARY(2048) NOT NULL,
    PasswordEnc  VARBINARY(2048) NOT NULL,
    UrlEnc       VARBINARY(2048) NOT NULL,
    CONSTRAINT fk_password_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE TOTP (
    ItemID      INT UNSIGNED PRIMARY KEY,
    SecretEnc   VARBINARY(2048) NOT NULL,
    Issuer      VARCHAR(255) NOT NULL,
    AccountName VARCHAR(255) NOT NULL,
    CONSTRAINT fk_totp_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PASSKEY (
    ItemID         INT UNSIGNED PRIMARY KEY,
    RpId           VARCHAR(255) NOT NULL,
    CredentialId   VARCHAR(2048) NOT NULL,
    PrivateKeyEnc  VARBINARY(4096) NOT NULL,
    CONSTRAINT fk_passkey_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE SECURE_NOTE (
    ItemID     INT UNSIGNED PRIMARY KEY,
    ContentEnc LONGBLOB NOT NULL,
    CONSTRAINT fk_note_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ATTACHMENT (
    AttachmentID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ItemID       INT UNSIGNED NOT NULL,
    FileName     VARCHAR(255) NOT NULL,
    MimeType     VARCHAR(127) NOT NULL,
    FileSize     BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CreatedAt    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachment_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE FILE_CHUNK (
    ChunkID       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    AttachmentID  INT UNSIGNED NOT NULL,
    ChunkNo       INT UNSIGNED NOT NULL,
    EncryptedData LONGBLOB NOT NULL,
    UNIQUE KEY uq_chunk (AttachmentID, ChunkNo),
    CONSTRAINT fk_chunk_attachment FOREIGN KEY (AttachmentID) REFERENCES ATTACHMENT(AttachmentID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CATEGORY (
    CategoryID   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID       INT UNSIGNED NOT NULL,
    CategoryName VARCHAR(128) NOT NULL,
    UNIQUE KEY uq_category (UserID, CategoryName),
    CONSTRAINT fk_category_user FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ITEM_CATEGORY (
    ItemID     INT UNSIGNED NOT NULL,
    CategoryID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ItemID, CategoryID),
    CONSTRAINT fk_ic_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE CASCADE,
    CONSTRAINT fk_ic_category FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE SHARE (
    ShareID    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ItemID     INT UNSIGNED NOT NULL,
    SharedBy   INT UNSIGNED NOT NULL,
    SharedWith INT UNSIGNED NOT NULL,
    Permission ENUM('READ','READ_WRITE') NOT NULL DEFAULT 'READ',
    CreatedAt  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_share_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE CASCADE,
    CONSTRAINT fk_share_by FOREIGN KEY (SharedBy) REFERENCES USER(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_share_with FOREIGN KEY (SharedWith) REFERENCES USER(UserID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE AUDIT_LOG (
    LogID     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID    INT UNSIGNED NOT NULL,
    ItemID    INT UNSIGNED NULL,
    Action    VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_audit_user (UserID),
    INDEX idx_audit_item (ItemID),
    CONSTRAINT fk_audit_user FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_audit_item FOREIGN KEY (ItemID) REFERENCES VAULT_ITEM(ItemID) ON DELETE SET NULL
) ENGINE=InnoDB;